language: java
jdk:
- oraclejdk8
script:
- mvn clean compile assembly:single

before_deploy:
- export FOO=$(ls target/batsy-rs-core-*.jar)

deploy:
  provider: releases
  api_key: ${api_key}
  file: "${FOO}"
  skip_cleanup: true
  on:
    tags: false
    #all_branches: true
branches:
      only:
      - master
      - /v\d+\.\d+[a-z]/
